name: vprofile actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: vprofile-eks
  ECR_REPOSITORY: vprofileapp

jobs:
  Testing:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
      
      #Setup java 11 to be default
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      #setup sonar scanner
      - name: SonarQube Scan
        run: sonar-scanner 
             -Dsonar.host.url=${{ secrets.SONAR_URL }}
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
              -Dsonar.sources=src/
              -Dsonar.junit.reportsPath=target/surefire-reports/ 
              -Dsonar.jacoco.reportsPath=target/jacoco.exec 
              -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
              -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/

      - name: SonarQube Quality Gate
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}